/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_BASE_STATION_PB_H_INCLUDED
#define PB_BASE_STATION_PB_H_INCLUDED
#include "utils/pb.h"
#include "gps.pb.h"
#include "motor.pb.h"
#include "version.pb.h"
#include "utils.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* / How the antenna is being controller. */
typedef enum _AntennaControlMode {
    AntennaControlMode_ANTENNA_CONTROL_MODE_UNDEFINED = 0,
    /* / The antenna should automatically move to track the rover's position. */
    AntennaControlMode_TRACK_ROVER = 1,
    /* / The antenna should only move when controlled manually by the operator. */
    AntennaControlMode_MANUAL_CONTROL = 2
} AntennaControlMode;

/* Struct definitions */
typedef struct _AntennaFirmwareCommand {
    bool has_version;
    Version version;
    bool has_swivel;
    MotorCommand swivel;
    bool stop;
    bool calibrate;
} AntennaFirmwareCommand;

typedef struct _AntennaFirmwareData {
    bool has_version;
    Version version;
    bool has_swivel;
    MotorData swivel;
    bool has_pitch;
    MotorData pitch;
} AntennaFirmwareData;

/* / Command to control the movement of the MARS antenna.
/
/ This command has two modes: manual operation or rover tracking.
/ - When tracking the rover, any GPS signals received by the rover or the base station's internal
/   GPS will cause it to re-calculate an orientation that ideally faces the rover. In this mode,
/   manual commands are ignored.
/ - When in manual mode, all GPS data is ignored and the motor is only moved when the Dashboard
/   sends a command with a [manual_command] payload.
/
/ When tracking the rover, the Dashboard can override either the base station or rover's position
/ for testing and debugging. When a new position override is received, the base station will:
/ - calculate the antenna orientation as if the rover were at this position
/ - send an [AntennaFirmwareCommand] for this position
/ - immediately set the [mode] to [AntennaControlMode.MANUAL_CONTROL] to hold the position */
typedef struct _BaseStationCommand {
    bool has_version;
    Version version;
    AntennaControlMode mode;
    bool has_rover_coordinates;
    GpsCoordinates rover_coordinates;
    bool has_base_station_coordinates;
    GpsCoordinates base_station_coordinates;
    bool has_rover_coordinates_override;
    GpsCoordinates rover_coordinates_override;
    bool has_manual_command;
    AntennaFirmwareCommand manual_command;
    /* The angle tolerance for auto-tracking, in radians */
    float angle_tolerance;
} BaseStationCommand;

typedef struct _BaseStationData {
    bool has_version;
    Version version;
    AntennaControlMode mode;
    bool has_antenna;
    AntennaFirmwareData antenna;
    bool has_base_station_coordinates;
    GpsCoordinates base_station_coordinates;
    /* Whether or not the RTK gps is open and being read */
    BoolState rtk_connected;
} BaseStationData;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _AntennaControlMode_MIN AntennaControlMode_ANTENNA_CONTROL_MODE_UNDEFINED
#define _AntennaControlMode_MAX AntennaControlMode_MANUAL_CONTROL
#define _AntennaControlMode_ARRAYSIZE ((AntennaControlMode)(AntennaControlMode_MANUAL_CONTROL+1))



#define BaseStationCommand_mode_ENUMTYPE AntennaControlMode

#define BaseStationData_mode_ENUMTYPE AntennaControlMode
#define BaseStationData_rtk_connected_ENUMTYPE BoolState


/* Initializer values for message structs */
#define AntennaFirmwareCommand_init_default      {false, Version_init_default, false, MotorCommand_init_default, 0, 0}
#define AntennaFirmwareData_init_default         {false, Version_init_default, false, MotorData_init_default, false, MotorData_init_default}
#define BaseStationCommand_init_default          {false, Version_init_default, _AntennaControlMode_MIN, false, GpsCoordinates_init_default, false, GpsCoordinates_init_default, false, GpsCoordinates_init_default, false, AntennaFirmwareCommand_init_default, 0}
#define BaseStationData_init_default             {false, Version_init_default, _AntennaControlMode_MIN, false, AntennaFirmwareData_init_default, false, GpsCoordinates_init_default, _BoolState_MIN}
#define AntennaFirmwareCommand_init_zero         {false, Version_init_zero, false, MotorCommand_init_zero, 0, 0}
#define AntennaFirmwareData_init_zero            {false, Version_init_zero, false, MotorData_init_zero, false, MotorData_init_zero}
#define BaseStationCommand_init_zero             {false, Version_init_zero, _AntennaControlMode_MIN, false, GpsCoordinates_init_zero, false, GpsCoordinates_init_zero, false, GpsCoordinates_init_zero, false, AntennaFirmwareCommand_init_zero, 0}
#define BaseStationData_init_zero                {false, Version_init_zero, _AntennaControlMode_MIN, false, AntennaFirmwareData_init_zero, false, GpsCoordinates_init_zero, _BoolState_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define AntennaFirmwareCommand_version_tag       1
#define AntennaFirmwareCommand_swivel_tag        2
#define AntennaFirmwareCommand_stop_tag          3
#define AntennaFirmwareCommand_calibrate_tag     4
#define AntennaFirmwareData_version_tag          1
#define AntennaFirmwareData_swivel_tag           2
#define AntennaFirmwareData_pitch_tag            3
#define BaseStationCommand_version_tag           1
#define BaseStationCommand_mode_tag              2
#define BaseStationCommand_rover_coordinates_tag 3
#define BaseStationCommand_base_station_coordinates_tag 4
#define BaseStationCommand_rover_coordinates_override_tag 5
#define BaseStationCommand_manual_command_tag    6
#define BaseStationCommand_angle_tolerance_tag   7
#define BaseStationData_version_tag              1
#define BaseStationData_mode_tag                 2
#define BaseStationData_antenna_tag              3
#define BaseStationData_base_station_coordinates_tag 4
#define BaseStationData_rtk_connected_tag        5

/* Struct field encoding specification for nanopb */
#define AntennaFirmwareCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  swivel,            2) \
X(a, STATIC,   SINGULAR, BOOL,     stop,              3) \
X(a, STATIC,   SINGULAR, BOOL,     calibrate,         4)
#define AntennaFirmwareCommand_CALLBACK NULL
#define AntennaFirmwareCommand_DEFAULT NULL
#define AntennaFirmwareCommand_version_MSGTYPE Version
#define AntennaFirmwareCommand_swivel_MSGTYPE MotorCommand

#define AntennaFirmwareData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  swivel,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pitch,             3)
#define AntennaFirmwareData_CALLBACK NULL
#define AntennaFirmwareData_DEFAULT NULL
#define AntennaFirmwareData_version_MSGTYPE Version
#define AntennaFirmwareData_swivel_MSGTYPE MotorData
#define AntennaFirmwareData_pitch_MSGTYPE MotorData

#define BaseStationCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           1) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rover_coordinates,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  base_station_coordinates,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rover_coordinates_override,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  manual_command,    6) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_tolerance,   7)
#define BaseStationCommand_CALLBACK NULL
#define BaseStationCommand_DEFAULT NULL
#define BaseStationCommand_version_MSGTYPE Version
#define BaseStationCommand_rover_coordinates_MSGTYPE GpsCoordinates
#define BaseStationCommand_base_station_coordinates_MSGTYPE GpsCoordinates
#define BaseStationCommand_rover_coordinates_override_MSGTYPE GpsCoordinates
#define BaseStationCommand_manual_command_MSGTYPE AntennaFirmwareCommand

#define BaseStationData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           1) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  antenna,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  base_station_coordinates,   4) \
X(a, STATIC,   SINGULAR, UENUM,    rtk_connected,     5)
#define BaseStationData_CALLBACK NULL
#define BaseStationData_DEFAULT NULL
#define BaseStationData_version_MSGTYPE Version
#define BaseStationData_antenna_MSGTYPE AntennaFirmwareData
#define BaseStationData_base_station_coordinates_MSGTYPE GpsCoordinates

extern const pb_msgdesc_t AntennaFirmwareCommand_msg;
extern const pb_msgdesc_t AntennaFirmwareData_msg;
extern const pb_msgdesc_t BaseStationCommand_msg;
extern const pb_msgdesc_t BaseStationData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AntennaFirmwareCommand_fields &AntennaFirmwareCommand_msg
#define AntennaFirmwareData_fields &AntennaFirmwareData_msg
#define BaseStationCommand_fields &BaseStationCommand_msg
#define BaseStationData_fields &BaseStationData_msg

/* Maximum encoded size of messages (where known) */
#define AntennaFirmwareCommand_size              51
#define AntennaFirmwareData_size                 104
#define BASE_STATION_PB_H_MAX_SIZE               BaseStationCommand_size
#define BaseStationCommand_size                  177
#define BaseStationData_size                     165

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
