/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "base_station.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AntennaFirmwareCommand, AntennaFirmwareCommand, AUTO)


PB_BIND(AntennaFirmwareData, AntennaFirmwareData, AUTO)


PB_BIND(BaseStationCommand, BaseStationCommand, AUTO)


PB_BIND(BaseStationData, BaseStationData, AUTO)





