/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GEOMETRY_PB_H_INCLUDED
#define PB_GEOMETRY_PB_H_INCLUDED
#include "utils/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Coordinates {
    float x;
    float y;
    float z;
} Coordinates;

typedef struct _Orientation {
    float x;
    float y;
    float z;
} Orientation;

typedef struct _Pose3d {
    bool has_translation;
    Coordinates translation;
    bool has_rotation;
    Orientation rotation;
} Pose3d;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Coordinates_init_default                 {0, 0, 0}
#define Orientation_init_default                 {0, 0, 0}
#define Pose3d_init_default                      {false, Coordinates_init_default, false, Orientation_init_default}
#define Coordinates_init_zero                    {0, 0, 0}
#define Orientation_init_zero                    {0, 0, 0}
#define Pose3d_init_zero                         {false, Coordinates_init_zero, false, Orientation_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Coordinates_x_tag                        1
#define Coordinates_y_tag                        2
#define Coordinates_z_tag                        3
#define Orientation_x_tag                        1
#define Orientation_y_tag                        2
#define Orientation_z_tag                        3
#define Pose3d_translation_tag                   1
#define Pose3d_rotation_tag                      2

/* Struct field encoding specification for nanopb */
#define Coordinates_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define Coordinates_CALLBACK NULL
#define Coordinates_DEFAULT NULL

#define Orientation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define Orientation_CALLBACK NULL
#define Orientation_DEFAULT NULL

#define Pose3d_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  translation,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rotation,          2)
#define Pose3d_CALLBACK NULL
#define Pose3d_DEFAULT NULL
#define Pose3d_translation_MSGTYPE Coordinates
#define Pose3d_rotation_MSGTYPE Orientation

extern const pb_msgdesc_t Coordinates_msg;
extern const pb_msgdesc_t Orientation_msg;
extern const pb_msgdesc_t Pose3d_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Coordinates_fields &Coordinates_msg
#define Orientation_fields &Orientation_msg
#define Pose3d_fields &Pose3d_msg

/* Maximum encoded size of messages (where known) */
#define Coordinates_size                         15
#define GEOMETRY_PB_H_MAX_SIZE                   Pose3d_size
#define Orientation_size                         15
#define Pose3d_size                              34

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
