/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "geometry.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Coordinates, Coordinates, AUTO)


PB_BIND(Orientation, Orientation, AUTO)


PB_BIND(Pose3d, Pose3d, AUTO)



