/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GPS_PB_H_INCLUDED
#define PB_GPS_PB_H_INCLUDED
#include "utils/pb.h"
#include "version.pb.h"
#include "geometry.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RTKMode {
    RTKMode_RTK_NONE = 0,
    RTKMode_RTK_FLOAT = 1,
    RTKMode_RTK_FIXED = 2
} RTKMode;

/* Struct definitions */
typedef struct _GpsCoordinates {
    double latitude;
    double longitude;
    double altitude;
    RTKMode rtk_mode;
} GpsCoordinates;

typedef struct _RoverPosition {
    bool has_gps;
    GpsCoordinates gps;
    bool has_orientation;
    Orientation orientation;
    bool has_version;
    Version version;
    pb_callback_t rtk_message;
} RoverPosition;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _RTKMode_MIN RTKMode_RTK_NONE
#define _RTKMode_MAX RTKMode_RTK_FIXED
#define _RTKMode_ARRAYSIZE ((RTKMode)(RTKMode_RTK_FIXED+1))

#define GpsCoordinates_rtk_mode_ENUMTYPE RTKMode



/* Initializer values for message structs */
#define GpsCoordinates_init_default              {0, 0, 0, _RTKMode_MIN}
#define RoverPosition_init_default               {false, GpsCoordinates_init_default, false, Orientation_init_default, false, Version_init_default, {{NULL}, NULL}}
#define GpsCoordinates_init_zero                 {0, 0, 0, _RTKMode_MIN}
#define RoverPosition_init_zero                  {false, GpsCoordinates_init_zero, false, Orientation_init_zero, false, Version_init_zero, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define GpsCoordinates_latitude_tag              1
#define GpsCoordinates_longitude_tag             2
#define GpsCoordinates_altitude_tag              3
#define GpsCoordinates_rtk_mode_tag              4
#define RoverPosition_gps_tag                    1
#define RoverPosition_orientation_tag            2
#define RoverPosition_version_tag                3
#define RoverPosition_rtk_message_tag            4

/* Struct field encoding specification for nanopb */
#define GpsCoordinates_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   latitude,          1) \
X(a, STATIC,   SINGULAR, DOUBLE,   longitude,         2) \
X(a, STATIC,   SINGULAR, DOUBLE,   altitude,          3) \
X(a, STATIC,   SINGULAR, UENUM,    rtk_mode,          4)
#define GpsCoordinates_CALLBACK NULL
#define GpsCoordinates_DEFAULT NULL

#define RoverPosition_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gps,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  orientation,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           3) \
X(a, CALLBACK, SINGULAR, BYTES,    rtk_message,       4)
#define RoverPosition_CALLBACK pb_default_field_callback
#define RoverPosition_DEFAULT NULL
#define RoverPosition_gps_MSGTYPE GpsCoordinates
#define RoverPosition_orientation_MSGTYPE Orientation
#define RoverPosition_version_MSGTYPE Version

extern const pb_msgdesc_t GpsCoordinates_msg;
extern const pb_msgdesc_t RoverPosition_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GpsCoordinates_fields &GpsCoordinates_msg
#define RoverPosition_fields &RoverPosition_msg

/* Maximum encoded size of messages (where known) */
/* RoverPosition_size depends on runtime parameters */
#define GPS_PB_H_MAX_SIZE                        GpsCoordinates_size
#define GpsCoordinates_size                      29

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
