/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "gps.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GpsCoordinates, GpsCoordinates, AUTO)


PB_BIND(Orientation, Orientation, AUTO)


PB_BIND(RoverPosition, RoverPosition, AUTO)



