/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "mars.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AntennaCommand, AntennaCommand, AUTO)


PB_BIND(AntennaMotorCommand, AntennaMotorCommand, AUTO)


PB_BIND(AntennaData, AntennaData, AUTO)


PB_BIND(BaseStationData, BaseStationData, AUTO)





