/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_MOTOR_PB_H_INCLUDED
#define PB_MOTOR_PB_H_INCLUDED
#include "utils/pb.h"
#include "utils.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _MotorDirection {
    MotorDirection_MOTOR_DIRECTION_UNDEFINED = 0,
    MotorDirection_UP = 1,
    MotorDirection_DOWN = 2,
    MotorDirection_LEFT = 3,
    MotorDirection_RIGHT = 4,
    MotorDirection_CLOCKWISE = 5,
    MotorDirection_COUNTER_CLOCKWISE = 6,
    MotorDirection_OPENING = 7,
    MotorDirection_CLOSING = 8,
    MotorDirection_NOT_MOVING = 9
} MotorDirection;

/* Struct definitions */
typedef struct _MotorData {
    BoolState is_moving;
    BoolState is_limit_switch_pressed;
    MotorDirection direction;
    int32_t current_step;
    int32_t target_step;
    float current_angle;
    float target_angle;
} MotorData;

typedef struct _MotorCommand {
    /* Debug control: Move by individual steps */
    int32_t move_steps;
    /* Precise control: Move by radians */
    float move_radians;
    /* / An angle to go to. Useful in IK. */
    float angle;
} MotorCommand;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MotorDirection_MIN MotorDirection_MOTOR_DIRECTION_UNDEFINED
#define _MotorDirection_MAX MotorDirection_NOT_MOVING
#define _MotorDirection_ARRAYSIZE ((MotorDirection)(MotorDirection_NOT_MOVING+1))

#define MotorData_is_moving_ENUMTYPE BoolState
#define MotorData_is_limit_switch_pressed_ENUMTYPE BoolState
#define MotorData_direction_ENUMTYPE MotorDirection



/* Initializer values for message structs */
#define MotorData_init_default                   {_BoolState_MIN, _BoolState_MIN, _MotorDirection_MIN, 0, 0, 0, 0}
#define MotorCommand_init_default                {0, 0, 0}
#define MotorData_init_zero                      {_BoolState_MIN, _BoolState_MIN, _MotorDirection_MIN, 0, 0, 0, 0}
#define MotorCommand_init_zero                   {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MotorData_is_moving_tag                  1
#define MotorData_is_limit_switch_pressed_tag    2
#define MotorData_direction_tag                  3
#define MotorData_current_step_tag               4
#define MotorData_target_step_tag                5
#define MotorData_current_angle_tag              6
#define MotorData_target_angle_tag               7
#define MotorCommand_move_steps_tag              1
#define MotorCommand_move_radians_tag            2
#define MotorCommand_angle_tag                   3

/* Struct field encoding specification for nanopb */
#define MotorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    is_moving,         1) \
X(a, STATIC,   SINGULAR, UENUM,    is_limit_switch_pressed,   2) \
X(a, STATIC,   SINGULAR, UENUM,    direction,         3) \
X(a, STATIC,   SINGULAR, INT32,    current_step,      4) \
X(a, STATIC,   SINGULAR, INT32,    target_step,       5) \
X(a, STATIC,   SINGULAR, FLOAT,    current_angle,     6) \
X(a, STATIC,   SINGULAR, FLOAT,    target_angle,      7)
#define MotorData_CALLBACK NULL
#define MotorData_DEFAULT NULL

#define MotorCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    move_steps,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    move_radians,      2) \
X(a, STATIC,   SINGULAR, FLOAT,    angle,             3)
#define MotorCommand_CALLBACK NULL
#define MotorCommand_DEFAULT NULL

extern const pb_msgdesc_t MotorData_msg;
extern const pb_msgdesc_t MotorCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MotorData_fields &MotorData_msg
#define MotorCommand_fields &MotorCommand_msg

/* Maximum encoded size of messages (where known) */
#define MOTOR_PB_H_MAX_SIZE                      MotorData_size
#define MotorCommand_size                        21
#define MotorData_size                           38

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
